In [3]:
import numpy as np

In [10]:
def python_sum(n):
    a=[i**2 for i in range(n)]
    b=[i**3 for i in range(n)]
    ab_sum = []
    for i in range(n):
        ab_sum.append(a[i]+b[i])
    return ab_sum

In [11]:
python_sum(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [8]:
def numpy_sum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    return a+b

In [9]:
numpy_sum(10)

array([ 0,  2, 12, 36], dtype=int32)

In [12]:
%timeit python_sum(10)

8.77 µs ± 230 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit numpy_sum(10)

3.08 µs ± 41.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


`numpy nbarray

In [14]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

元组

In [15]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

迭代对象

In [16]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

生成器

In [18]:
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

二维数组

In [21]:
ar=np.array([[1,2,3],('a','b','c')])

秩、维度、总个数、每个元素大小

In [49]:
ar.ndim

2

In [48]:
ar.shape

(2, 3)

In [46]:
ar.size

6

In [47]:
ar.itemsize

4

调整维度reshape

In [56]:
n=np.arange(20).reshape((4,5))
print(n)
n[...,1]#返回第二列
n[...,1:]#返回第二列后所有项
n[...][1]#返回第二行

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([5, 6, 7, 8, 9])

调整维度resize

In [52]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

arange生成区间数组 numpy.arange(start,stop,step,dtype)

In [51]:
np.arange(10)
np.arange(2,5)
np.arange(4.8)
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

在庆祝教师节活动中，学校为了烘托气氛，在200米长的校园一侧，从起点开始，每间隔3米插一次彩旗，会到终点吗？一共几面？

In [33]:
np.arange(0,200+1,3)

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198])

In [34]:
len(np.arange(0,200+1,3))

67

linspace等差数列 linspace(start,stop,num,endpoint为true时包含终止值,retstep为true时显示间距,dtype)

In [40]:
np.linspace(0, 4.1, 9,retstep = True)

(array([0.    , 0.5125, 1.025 , 1.5375, 2.05  , 2.5625, 3.075 , 3.5875,
        4.1   ]),
 0.5125)

logspace等比数列，logspace(start,stop,num,endpoint为true时包含终止值,base对数log的底数,dtype)

In [41]:
np.logspace(0,9,10,base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

全0数列 numpy.zeros(shape,dtype=float,order='C'

In [42]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [44]:
#zeros_like返回具有与给定数组相同的形状和类型的零数组
ar=np.array([[1,2,3],[4,5,6]])
np.zeros_like(ar)

array([[0, 0, 0],
       [0, 0, 0]])

全一数列 numpy.ones(shape,dtype=float,order='C')

整数数组索引

In [60]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
y

array([1, 4, 5])

布尔数值索引
提取出数组中所有奇数，修改奇数值为-1

In [63]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
x[x%2==1]=-1
x

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

In [64]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
x[(x>4)&(x<9)]#|或

array([5, 6, 7, 8])

用true和false挑选要和不要的元素

In [74]:
a = np.arange(12).reshape((3,4))
raw = np.array([False,True,True])
col = np.array([False,True,False,True])
a[raw]
a[:,col]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [71]:
raw = np.array([False,True,True])

array([], shape=(0, 3, 4), dtype=int32)

In [75]:
a = np.arange(12).reshape((3,4))
a[[0,-1],:][:,[0,2,3]]#先选行，再要列

array([[ 0,  2,  3],
       [ 8, 10, 11]])

平均值,中位数,标准差,方差,最大值,最小值,求和

In [86]:
a.mean()
a.mean(axis=0)#等于0为从上往下，1为从左往右
np.median(a)
np.std(a)
np.var(a)
np.max(a)
np.min(a)
np.sum(a)

66

加权平均值

In [87]:
a = np.array([90,90,95])
w = np.array([0.2,0.3,0.5])
np.average(a,weights=w)

92.5

变异系数(Coefficient of Variation)当需要比较两组数据离散程度大小的时候，如果两组差异过大，可以用变异系数来消除测量尺度和量纲的影响#变异系数 = 标准差/平均数

结构化信息

In [93]:
teacher = np.dtype([('name',np.str_,2),('age','i1'),('salary','f4')])
b = np.array([('w1',32,8354)],dtype = teacher)
print(b)

[('w1', 32, 8354.)]


操作文件 loadtxt(fname,dtype,comments,delimiter,converters,skiprows跳过的行数,usecols,unpack是否转置,ndmin,encoding)

In [98]:
data = np.loadtxt('data.txt')
print(data,data.shape)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]] (2, 6)


In [106]:
np.random.rand(4,2)#0到1之间的随机数

array([[0.04800857, 0.94703037],
       [0.56917301, 0.81631278],
       [0.66440689, 0.21896034],
       [0.52593952, 0.45517473]])

In [107]:
np.random.randn(4)#一组标准正态分布的样本

array([-0.89275868,  0.88143488, -0.77039243,  0.64295518])

In [109]:
np.random.randint(-5,5,size=(2,2))#-5到5之间的随机数

array([[-4,  2],
       [ 3, -1]])

In [110]:
np.random.sample((2,3))#返回[0.0,1.0]之间的随机数

array([[0.95626229, 0.52836132, 0.67855222],
       [0.94247524, 0.25564337, 0.78003721]])

In [111]:
np.random.seed(1)#保证生成的随机数相同
L1 = np.random.randn(3,3)

In [116]:
a = np.array([[1,2,3],[4,5,6]])
a.resize((3,3),refcheck=False)
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

numpy.append()/numpy.insert()/numpy.delete()/numpy.argwhere()返回非0元素的索引，可带条件/numpy.unique()删除重复/numpy.sort